version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "13000:13000"
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=user123
      - POSTGRES_DB=db123
      - DB_HOST=db
